name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Windows Insider Build (xxxxx)"
        - "Windows 11 (22H2): Build 22621"
        - "Windows 11 (21H2): Build 22000"
        - "Windows 10 (21H2): Build 19044"
        - "Windows 10 (21H1): Build 19043"
        - "Windows 10 (20H2): Build 19042"
        - "Windows 10 (2004): Build 19041"
        - "Windows 10 (1909): Build 18363"
        - "Windows 10 (1903): Build 18362"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
