name: Feature Proposal
description: Suggest a new feature or idea
title: "[Proposal]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature proposal!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature
      description: Please enter a short, clear description of the feature.
      placeholder: Merge multiple images from files or clipboard, including screenshots, into a new file.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Main points of feature
      description: Please provide important points that are the purpose and use of the feature.
      placeholder: |
        - Add multiple images from file and last item from clipboard.
        - Drag-and-drop image files are also supported.
        - Compress images to make the final file lighter.
        - Stack images by horizontal or vertical direction.
        - Merge all images into a new file in .png, .jpeg, or .pdf format.
  - type: textarea
    attributes:
      label: Reasons to develop
      description: Please provide some reasons why this feature should be developed.
      placeholder: |
        1. It is very useful for many people.
        2. It really helps people's work.
        3. It can save a lot of time.
  - type: textarea
    attributes:
      label: Blueprints
      description: If possible, it can help in the implementation process.
